require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DjsController do

  # This should return the minimal set of attributes required to create a valid
  # Dj. As you add validations to Dj, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DjsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all djs as @djs" do
      dj = Dj.create! valid_attributes
      get :index, {}, valid_session
      assigns(:djs).should eq([dj])
    end
  end

  describe "GET show" do
    it "assigns the requested dj as @dj" do
      dj = Dj.create! valid_attributes
      get :show, {:id => dj.to_param}, valid_session
      assigns(:dj).should eq(dj)
    end
  end

  describe "GET new" do
    it "assigns a new dj as @dj" do
      get :new, {}, valid_session
      assigns(:dj).should be_a_new(Dj)
    end
  end

  describe "GET edit" do
    it "assigns the requested dj as @dj" do
      dj = Dj.create! valid_attributes
      get :edit, {:id => dj.to_param}, valid_session
      assigns(:dj).should eq(dj)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dj" do
        expect {
          post :create, {:dj => valid_attributes}, valid_session
        }.to change(Dj, :count).by(1)
      end

      it "assigns a newly created dj as @dj" do
        post :create, {:dj => valid_attributes}, valid_session
        assigns(:dj).should be_a(Dj)
        assigns(:dj).should be_persisted
      end

      it "redirects to the created dj" do
        post :create, {:dj => valid_attributes}, valid_session
        response.should redirect_to(Dj.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dj as @dj" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dj.any_instance.stub(:save).and_return(false)
        post :create, {:dj => {}}, valid_session
        assigns(:dj).should be_a_new(Dj)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dj.any_instance.stub(:save).and_return(false)
        post :create, {:dj => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dj" do
        dj = Dj.create! valid_attributes
        # Assuming there are no other djs in the database, this
        # specifies that the Dj created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dj.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dj.to_param, :dj => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dj as @dj" do
        dj = Dj.create! valid_attributes
        put :update, {:id => dj.to_param, :dj => valid_attributes}, valid_session
        assigns(:dj).should eq(dj)
      end

      it "redirects to the dj" do
        dj = Dj.create! valid_attributes
        put :update, {:id => dj.to_param, :dj => valid_attributes}, valid_session
        response.should redirect_to(dj)
      end
    end

    describe "with invalid params" do
      it "assigns the dj as @dj" do
        dj = Dj.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dj.any_instance.stub(:save).and_return(false)
        put :update, {:id => dj.to_param, :dj => {}}, valid_session
        assigns(:dj).should eq(dj)
      end

      it "re-renders the 'edit' template" do
        dj = Dj.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dj.any_instance.stub(:save).and_return(false)
        put :update, {:id => dj.to_param, :dj => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dj" do
      dj = Dj.create! valid_attributes
      expect {
        delete :destroy, {:id => dj.to_param}, valid_session
      }.to change(Dj, :count).by(-1)
    end

    it "redirects to the djs list" do
      dj = Dj.create! valid_attributes
      delete :destroy, {:id => dj.to_param}, valid_session
      response.should redirect_to(djs_url)
    end
  end

end
